# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora_Científica.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalculadoraCientifica(object):
    def setupUi(self, CalculadoraCientifica):
        CalculadoraCientifica.setObjectName("CalculadoraCientifica")
        CalculadoraCientifica.resize(500, 333)
        CalculadoraCientifica.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        CalculadoraCientifica.setFont(font)
        CalculadoraCientifica.setMouseTracking(False)
        self.layoutWidget = QtWidgets.QWidget(CalculadoraCientifica)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 315))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tres = QtWidgets.QPushButton(self.layoutWidget)
        self.tres.setObjectName("tres")
        self.gridLayout.addWidget(self.tres, 6, 3, 1, 2)
        self.dois = QtWidgets.QPushButton(self.layoutWidget)
        self.dois.setObjectName("dois")
        self.gridLayout.addWidget(self.dois, 6, 1, 1, 2)
        self.voltar = QtWidgets.QPushButton(self.layoutWidget)
        self.voltar.setObjectName("voltar")
        self.gridLayout.addWidget(self.voltar, 7, 0, 1, 1)
        self.um = QtWidgets.QPushButton(self.layoutWidget)
        self.um.setObjectName("um")
        self.gridLayout.addWidget(self.um, 6, 0, 1, 1)
        self.cinco = QtWidgets.QPushButton(self.layoutWidget)
        self.cinco.setObjectName("cinco")
        self.gridLayout.addWidget(self.cinco, 5, 1, 1, 2)
        self.quatro = QtWidgets.QPushButton(self.layoutWidget)
        self.quatro.setObjectName("quatro")
        self.gridLayout.addWidget(self.quatro, 5, 0, 1, 1)
        self.mais = QtWidgets.QPushButton(self.layoutWidget)
        self.mais.setObjectName("mais")
        self.gridLayout.addWidget(self.mais, 6, 5, 1, 1)
        self.seis = QtWidgets.QPushButton(self.layoutWidget)
        self.seis.setObjectName("seis")
        self.gridLayout.addWidget(self.seis, 5, 3, 1, 2)
        self.menos = QtWidgets.QPushButton(self.layoutWidget)
        self.menos.setObjectName("menos")
        self.gridLayout.addWidget(self.menos, 5, 5, 1, 1)
        self.sete = QtWidgets.QPushButton(self.layoutWidget)
        self.sete.setObjectName("sete")
        self.gridLayout.addWidget(self.sete, 4, 0, 1, 1)
        self.nove = QtWidgets.QPushButton(self.layoutWidget)
        self.nove.setObjectName("nove")
        self.gridLayout.addWidget(self.nove, 4, 3, 1, 2)
        self.C = QtWidgets.QPushButton(self.layoutWidget)
        self.C.setObjectName("C")
        self.gridLayout.addWidget(self.C, 3, 0, 1, 1)
        self.raiz = QtWidgets.QPushButton(self.layoutWidget)
        self.raiz.setObjectName("raiz")
        self.gridLayout.addWidget(self.raiz, 3, 1, 1, 2)
        self.apaga = QtWidgets.QPushButton(self.layoutWidget)
        self.apaga.setObjectName("apaga")
        self.gridLayout.addWidget(self.apaga, 3, 3, 1, 2)
        self.display = QtWidgets.QLabel(self.layoutWidget)
        self.display.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setText("")
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 1, 0, 1, 6)
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.gridLayout.addWidget(self.titulo, 0, 0, 1, 6)
        self.divisao = QtWidgets.QPushButton(self.layoutWidget)
        self.divisao.setObjectName("divisao")
        self.gridLayout.addWidget(self.divisao, 3, 5, 1, 1)
        self.zero = QtWidgets.QPushButton(self.layoutWidget)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 7, 3, 1, 2)
        self.cos = QtWidgets.QPushButton(self.layoutWidget)
        self.cos.setObjectName("cos")
        self.gridLayout.addWidget(self.cos, 2, 1, 1, 2)
        self.vezes = QtWidgets.QPushButton(self.layoutWidget)
        self.vezes.setObjectName("vezes")
        self.gridLayout.addWidget(self.vezes, 4, 5, 1, 1)
        self.oito = QtWidgets.QPushButton(self.layoutWidget)
        self.oito.setObjectName("oito")
        self.gridLayout.addWidget(self.oito, 4, 1, 1, 2)
        self.virgula = QtWidgets.QPushButton(self.layoutWidget)
        self.virgula.setObjectName("virgula")
        self.gridLayout.addWidget(self.virgula, 7, 1, 1, 2)
        self.tg = QtWidgets.QPushButton(self.layoutWidget)
        self.tg.setObjectName("tg")
        self.gridLayout.addWidget(self.tg, 2, 3, 1, 2)
        self.igual = QtWidgets.QPushButton(self.layoutWidget)
        self.igual.setObjectName("igual")
        self.gridLayout.addWidget(self.igual, 7, 5, 1, 1)
        self.sen = QtWidgets.QPushButton(self.layoutWidget)
        self.sen.setObjectName("sen")
        self.gridLayout.addWidget(self.sen, 2, 0, 1, 1)
        self.pow = QtWidgets.QPushButton(self.layoutWidget)
        self.pow.setObjectName("pow")
        self.gridLayout.addWidget(self.pow, 2, 5, 1, 1)

        self.retranslateUi(CalculadoraCientifica)
        QtCore.QMetaObject.connectSlotsByName(CalculadoraCientifica)

    def retranslateUi(self, CalculadoraCientifica):
        _translate = QtCore.QCoreApplication.translate
        CalculadoraCientifica.setWindowTitle(_translate("CalculadoraCientifica", "Calculadora Científica"))
        self.tres.setText(_translate("CalculadoraCientifica", "3"))
        self.dois.setText(_translate("CalculadoraCientifica", "2"))
        self.voltar.setText(_translate("CalculadoraCientifica", "Voltar"))
        self.um.setText(_translate("CalculadoraCientifica", "1"))
        self.cinco.setText(_translate("CalculadoraCientifica", "5"))
        self.quatro.setText(_translate("CalculadoraCientifica", "4"))
        self.mais.setText(_translate("CalculadoraCientifica", "+"))
        self.seis.setText(_translate("CalculadoraCientifica", "6"))
        self.menos.setText(_translate("CalculadoraCientifica", "-"))
        self.sete.setText(_translate("CalculadoraCientifica", "7"))
        self.nove.setText(_translate("CalculadoraCientifica", "9"))
        self.C.setText(_translate("CalculadoraCientifica", "C"))
        self.raiz.setText(_translate("CalculadoraCientifica", "sqrt(x)"))
        self.apaga.setText(_translate("CalculadoraCientifica", "<--"))
        self.titulo.setText(_translate("CalculadoraCientifica", "CALCULADORA CIENTÍFICA"))
        self.divisao.setText(_translate("CalculadoraCientifica", "/"))
        self.zero.setText(_translate("CalculadoraCientifica", "0"))
        self.cos.setText(_translate("CalculadoraCientifica", "cos(x)"))
        self.vezes.setText(_translate("CalculadoraCientifica", "*"))
        self.oito.setText(_translate("CalculadoraCientifica", "8"))
        self.virgula.setText(_translate("CalculadoraCientifica", "."))
        self.tg.setText(_translate("CalculadoraCientifica", "tan(x)"))
        self.igual.setText(_translate("CalculadoraCientifica", "="))
        self.sen.setText(_translate("CalculadoraCientifica", "sin(x)"))
        self.pow.setText(_translate("CalculadoraCientifica", "**"))

